name:                flabbergast
version:             0.1.0.0
github:              "cbiffle/flabbergast-hs"
license:             BSD3
author:              "Cliff L. Biffle"
maintainer:          "code@cliffle.com"
copyright:           "2018 Cliff L. Biffle"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cbiffle/flabbergast-hs#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring

data-files:
- bench/dict.txt

ghc-options:
- -fwarn-unused-imports
- -O2

library:
  source-dirs: src
  dependencies:
  - bytestring-trie
  - containers
  - criterion
  - deepseq
  - hashable
  - QuickCheck
  - split
  - unordered-containers
  - vector
  - heaps
  - mtl

executables:
  solver:
    main:                Main.hs
    source-dirs:         bin
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flabbergast

tests:
  tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flabbergast
    - hspec
    - QuickCheck
    - split
  weigh:
    main:                Main.hs
    source-dirs:         weigh
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - flabbergast
    - weigh
    - deepseq

benchmarks:
  best:
    source-dirs:  bench
    main:         Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - flabbergast
    - criterion
    - deepseq
  all:
    source-dirs:  bench-all
    main:         Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - flabbergast
    - criterion
    - deepseq
